### ISSUE TITLE
Build fails when using &macro_press, &macro_wait_for_release, and &macro_release in macros.dtsi

### ISSUE THREAD

**Issue by ringil-forge** [KinesisCorporation/Adv360-Pro-ZMK#11]
When adding a macro that uses syntax from the ZMK Macro Documentation, the build fails with the errors:
```
adv360_left.dts.pre.tmp:784.42-793.3: ERROR (phandle_references): /behaviors/macro_vscode_format: Reference to non-existent node or label "macro_press"

adv360_left.dts.pre.tmp:784.42-793.3: ERROR (phandle_references): /behaviors/macro_vscode_format: Reference to non-existent node or label "macro_pause_for_release"

adv360_left.dts.pre.tmp:784.42-793.3: ERROR (phandle_references): /behaviors/macro_vscode_format: Reference to non-existent node or label "macro_release"
```

I added a macro [following the documentation](https://zmk.dev/docs/behaviors/macros) creating a macro w/ `&macro_press` like in the below example pulled from the docs:
```
bindings
    = <&macro_press &kp LSHFT>
    , <&macro_tap &kp Z &kp M &kp K>
    , <&macro_release &kp LSHFT>
    ;
```

I am attempting to create a macro that will run the VSCode format keyboard shortcut, which entails chording 3 keys together, I added my macro as:
```
macro_vscode_format: macro_vscode_format {
    label = "macro_vscode_format";
    compatible = "zmk,behavior-macro";
    #binding-cells = <0>;
    bindings
        = <&macro_press &kp LSHFT &kp LALT &kp F>
        , <&macro_pause_for_release>
        , <&macro_release &kp LSHFT &kp LALT &kp F>
        ;
};
```
And got the above referenced [build error](https://github.com/mpentecost/Adv360-Pro-ZMK/actions/runs/3078730420/jobs/4974471159).

What am I doing wrong?

**Comment by arogulin** [comment]
@mpentecost I had [exact same issue](https://github.com/arogulin/Adv360-Pro-ZMK/actions/runs/3085699676/jobs/4989284530) trying to create macros to execute `CMD+c` and `CMD+v` actions. I tried the following code and it failed exactly as yours:
```
  macro_cmd_c: macro_cmd_c {
    label = "macro_cmd_c";
    compatible = "zmk,behavior-macro";
    #binding-cells = <0>;
    bindings
        = <&macro_press &kp LGUI>
        , <&macro_tap &kp C>
        , <&macro_release &kp LGUI>
        ;
  };

  macro_cmd_v: macro_cmd_v {
    label = "macro_cmd_v";
    compatible = "zmk,behavior-macro";
    #binding-cells = <0>;
    bindings
        = <&macro_press &kp LGUI>
        , <&macro_tap &kp V>
        , <&macro_release &kp LGUI>
        ;
  };
```

Not sure what the root cause is, but I noticed Kinesis uses key codes like `LS(something)` in their macros.dtsi and I assumed `LS` could mean `LSHIFT`, which turned out to be true: https://zmk.dev/docs/codes#modifiers. That meant I don't even need a macro definition anymore, so I simply used `&kp LG(C)` and `&kp LG(V)` in `adv360.keymap` (see this [commit](https://github.com/arogulin/Adv360-Pro-ZMK/commit/4d755f2f4c2ef0ff8bb5d805ed98db8cd847f1dd)), where `LG` means `LGUI`. 
I think they could be stackable, so your macro could probably be replaced with something like `&kp LS(LA(F))`. Try it and see if it works.

**Comment by KinesisCorporation** [comment]
@arogulin is correct to the best of our knowledge.

**Comment by arogulin** [comment]
I should have read the whole documentation page instead of making my assumptions: these are called `modifier functions` and they are indeed stackable, that page I linked above has this example at the [bottom](https://zmk.dev/docs/codes/modifiers#modifier-functions):
```
* They can be combined:
  * &kp LC(RA(B)) = LEFT_CONTROL+RIGHT_ALT+B
```

**Comment by ringil-forge** [comment]
@arogulin Thank you, those modifier functions work out well for my use case.

**Comment by ringil-forge** [comment]
I can confirm that macro syntax like:
```
bindings
    = <&macro_press &kp LSHFT>
    , <&macro_tap &kp Z &kp M &kp K>
    , <&macro_release &kp LSHFT>
    ;
```

Works w/ the new V2.0-beta branch.
