### ISSUE TITLE
Bluetooth only connects to one Operating System on dual-boot systems

### ISSUE THREAD

**Issue by Schilt** [KinesisCorporation/Adv360-Pro-ZMK#34]
I have dual boot systems with Windows and Ubuntu GNU/Linux.  The keyboard using bluetooth will only connect to one operating system on an individual PC.  It won't connect to both.  My Logitech MX Anywhere mouse though does connect to both systems.  I am only using one Operating System at a time, of course.  I am using the multiple device connections feature of the keyboard.  Other than this it works well!  Thanks!

**Comment by abenz1267** [comment]
see here: https://github.com/zmkfirmware/zmk/issues/1503

**Comment by ReFil** [comment]
As the other issue mentions this is because ZMK is strict with bluetooth security and doesn't allow different keys for the same physical device. There's a workaround for the time being. I do not plan on changing the bluetooth security behaviour until the recquisite changes are implemented in ZMK main
