### ISSUE TITLE
Is it possible to switch layout with different profiles?

### ISSUE THREAD

**Issue by mertzjames** [KinesisCorporation/Adv360-Pro-ZMK#97]
I have a Mac, Windows, and Linux machine that I'm connecting to my Kinesis Advantage 360 Pro to.  I was wondering if there was a way to switch profiles and layouts for each of those.  I really liked the ability to switch the Windows, Command, and Home keys on my old Advantage 2.

**Comment by ReFil** [comment]
You could use a macro to execute the layer swap and profile swap with one keypress

**Comment by ReFil** [comment]
Hi, just following up on this, has this issue been solved? if i dont hear back in 24h i will close out the issue

**Comment by itsthejoker** [comment]
I wrote my own macro for this -- you can take a look at my repo for how to do it yourself. https://github.com/itsthejoker/Adv360-Pro-ZMK

**Comment by KinesisCorporation** [comment]
@mertzjames closing the issue for now. Please reopen if you aren't able to get it to work.

@itsthejoker thanks for sharing!!!

**Comment by itsthejoker** [comment]
@mertzjames just fyi I updated my repo with the Mac layer to the latest V2 firmware, since my fork was previously the day 1 release.

**Comment by mertzjames** [comment]
@itsthejoker I'm just now seeing this.  Sorry.  It's been a busy couple of weeks/months for me. Thanks for putting this together.  I'm going to go over it later today but do you have a quick and dirty overview of what I should look at?  I'm still pretty new to ZMK and the layouts.  Is there documentation of the different key codes and how to use Macros to switch layouts?

**Comment by itsthejoker** [comment]
The only file you should really need is [adv360.keymap](https://github.com/itsthejoker/Adv360-Pro-ZMK/blob/main/config/adv360.keymap) -- the way it works is that I added a layer at the second position where all the keys are transparent except for the mac-specific ones and made the modifier key enable / disable this mostly-transparent layer with MOD+M.

If you want to be able to work with the keymap in the online tool, you'll have to make sure that the [keymap.json](https://github.com/itsthejoker/Adv360-Pro-ZMK/blob/main/config/keymap.json) file is kept up-to-date as well; otherwise it will just overwrite your changes to `adv360.keymap` any time you use it.

Here's the [full keycode list](https://zmk.dev/docs/codes) -- you can follow the existing patterns in the file along with those codes to make any key do anything. Good luck!

**Comment by itsthejoker** [comment]
@mertzjames FYI I finally got off my ass and updated my repo to v3. If you just want to install my version, then Mod+M will enable mac-specific keys. https://github.com/itsthejoker/Adv360-Pro-ZMK
